### ISSUE TITLE
Add Twitter icon next to Facebook and Github

### ISSUE THREAD

**Issue by howawong** [g0vhk-io/budgetq#19]
The twitter link is https://twitter.com/g0vhk_io
Please add twitter icon next to github icon
![screen shot 2018-04-01 at 9 26 33 pm](https://user-images.githubusercontent.com/760880/38173594-66732a20-35f3-11e8-8f76-f4f9fd8b4c8a.png)

**Comment by wingkwong** [comment]
created pull request #21
