### ISSUE TITLE
Improve Facebook Sharing

### ISSUE THREAD

**Issue by howawong** [g0vhk-io/budgetq#6]
1. Provide generated og:image image per reply
2. Server Side Rendering for `/reply/{ID}` page

**Comment by howawong** [comment]
For 1. I think we can generate graphics at g0vhk-io/legco-api-server
For 2. We need to change budgetq project, currently we are using create-react-app which does not include server side rendering.

**Comment by tonyhhyip** [comment]
I am working on 2

**Comment by howawong** [comment]
@tonyhhyip how do you tackle with the issue? Using express?

**Comment by tonyhhyip** [comment]
@howawong I am considering in picking either directly adding ssr in express or having ssr with the power of [next.js](https://github.com/zeit/next.js/). Please allow me to provide more information on Monday.

**Comment by tonyhhyip** [comment]
After reading thought different document, I would suggest using next.js with some custom server config

**Comment by howawong** [comment]
#12 #13 handles SSR. Closing this issue and continue at #14
