### ISSUE TITLE
Improve Facebook Share Button

### ISSUE THREAD

**Issue by howawong** [g0vhk-io/budgetq#7]
Currently, in [reply detail](https://budgetq.g0vhk.io/reply/2017-DEVB(PL)001) the "分享" button is just a HTML link element.
![screen shot 2018-03-09 at 8 27 16 am](https://user-images.githubusercontent.com/760880/37183965-bb8b395e-2373-11e8-9acb-290ec4dfe138.png)

Better improve it to be raised button or integrate with Facebook social plugin.

**Comment by zerg000000** [comment]
did you have facebook appId for your website?

**Comment by howawong** [comment]
Seems not, I think I need to create an app later,  anyway, I think 8e9966a looks fine to me. Will merge it soon.
